const items = [
    {
        id: 0,
        content: "Reversi.mp4",
        contentType: "video",
        alt: "Reversi AI Bot",
        category: "cs",
        skills: ["java","bash","vscode"],
        description: "An alphabeta pruning algorithm to evaluate the optimal move to make in Reversi by calculating multiple moves ahead. The Artificial Inteligence uses weights of priority locations on the board using bitmaps.",
    },
    {
        id: 1,
        content: "Value_Iteration.mp4",
        contentType: "video",
        alt: "Value Iteration",
        category: "cs",
        skills: ["java","bash","vscode"],
        description: "Using bayes filter to generate beliefs about the robot's surroundings and uses value iteration to determine the movements it should make given the beliefs that are simulated.",
    },
    {
        id: 2,
        content: "Solar_Wires.mp4",
        contentType: "video",
        alt: "Solar Wire FX",
        category: "cs",
        skills: ["unreal","maya"],
        description: "A procedural wire that traces the hexagons from each individual solar tower to the home base. I used Blueprints in Unreal Engine to recursively run through points on a spline and that spline is used to generate the wire geometry and used as a path for the solar energy to move across.",
    },
    {
        id: 3,
        content: "HexagonPath.mp4",
        contentType: "video",
        alt: "Proximity Based Geometry and Shader Manipulation",
        category: "cs",
        skills: ["unreal"],
        description: "A grid of hexagonal objects manipulated using player proximity to change shaders and object height.",
    },
    {
        id: 4,
        content: "OpenGL.mp4",
        contentType: "video",
        alt: "OpenGL",
        category: "cs",
        skills: ["python","vscode"],
        description: "Rendering use transformation matrices, clipping, and projection to emulate camera movement and animations using Pygame.",
    },
    {
        id: 5,
        content: "Twitter_Clone.mp4",
        contentType: "video",
        alt: "Twitter Clone",
        category: "cs",
        skills: ["java","android","intellij","aws"],
        description: "The result of building a Twitter clone Android app in 14 weeks from the ground up. It is missing much of the functionality because it was no longer connected to the database that was hosted through DynamoDB. This project used AWS APIGateway for endpoints, DynamoDB as a database, S3 Buckets for storage, and Cognito for authentication. The code was all written from scratch in Java, for both the backend server and front end. I worked with another student and we used a mixture of Intellij and Android Studio.",
    },
    // {
    //     id: 6,
    //     content: "FarmhouseModel.mp4",
    //     contentType: "video",
    //     alt: "Silo Model",
    //     category: "art",
    //     skills: ["maya"],
    //     description: "A model created in Maya. I took it from the proxy stage to a high-poly, more detailed model. This model is the farmer's home base in BYU's tower defense RTS, Solar Showdown (2022-2023). I completed the Silo and Claw models.",
    // },
    {
        id: 6,
        content: "Farmhouse_Animation.mp4",
        contentType: "video",
        alt: "Silo Rig",
        category: "art",
        skills: ["maya"],
        description: "I modeled, rigged and animated the home base claw and silo for Solar Showdown (2022-2023). The rig implements ik and fk controls, conditional parenting the silo to the claw, and scripting that zeroes out controls, matches ik to fk, and vice versa. The ik skeleton was implemented with a spline ik curve that uses the shape of the curve to control the claw cable shape.",
    },
    {
        id: 7,
        content: "TurretAnim.mp4",
        contentType: "video",
        alt: "Turret Animation",
        category: "art",
        skills: ["maya","unreal"],
        description: "I animated the farmer's turret for Solar Showdown and implemented the blueprint logic in unreal engine 5. The turret changes states based on the upgrades it has and transitions are seamless for each mode.",
    },
    // {
    //     id: 8,
    //     content: "BotanistSolarTower_Turnaround.mp4",
    //     contentType: "video",
    //     alt: "Solar Tower Proxy Model",
    //     category: "art",
    //     skills: ["maya"],
    //     description: "A proxy model created for Solar Showdown of the Solar Towers used as the main win condition of the game. Modeling work was all done in Maya.",
    // },
    {
        id: 9,
        content: "Piano_Turnaround.mp4",
        contentType: "video",
        alt: "Piano Model",
        category: "art",
        skills: ["blender"],
        description: "A piano model I had modeled over the summer to practice procedural modeling techniques and unique shaders. The piano keys were generated using an array that follows a curve.",
    },
    {
        id: 10,
        content: "Laptop_Turnaround.mp4",
        contentType: "video",
        alt: "Laptop",
        category: "art",
        skills: ["blender"],
        description: "A recreation of my current laptop in Blender. All textures and modeling was done in Blender. This is one of many projects I have started to recreate my belongings through 3D Modeling. This model took a bit of array knowledge and spacing things just right to get the keyboard to align correctly.",
    },
    {
        id: 11,
        content: "GameCube_Turnaround.mp4",
        contentType: "video",
        alt: "GameCube",
        category: "art",
        skills: ["blender"],
        description: "A model of a Gamecube I made in Blender. I am a big fan of the GameCube. It had a bunch of great games. I learned some great edge flow techniques and topology problems when working on this model. I can better keep poly count in check now because of this project.",
    },
    {
        id: 12,
        content: "Controller_Turnaround.mp4",
        contentType: "video",
        alt: "Controller",
        category: "art",
        skills: ["blender"],
        description: "A model of a Gamecube controller made in Blender. My personal favorite controller. This project took a bit of thought to get the form looking good as its shape is very unorthodox with half rounded buttons and the shaping of the handholds into hard edges took careful consideration.",
    },
    {
        id: 13,
        content: "Makoto_Turnaround.mp4",
        contentType: "video",
        alt: "Makoto Sculpt",
        category: "art",
        skills: ["zbrush","blender"],
        description: "A sculpt of the character Makoto from Street Fighter. I made this during my 14 day free trial of ZBrush. I had never used Zbrush before and I think I got the hang of many of the important tools while working on this sculpt. The turnaround was rendered in Blender.",
    },
    {
        id: 14,
        content: "Daisy_Turnaround.mp4",
        contentType: "video",
        alt: "Daisy Model",
        category: "art",
        skills: ["blender"],
        description: "A character model I am working on to improve my character modeling and sculpting skills. All sculpting and modeling was done in Blender. The model is inspired by a concept made by @AutomaticGiraffe of the character Daisy from the Mario franchise. My main goal with this piece was to improve sculpting the face and better work with hair sculpts.",
    },
    // {
    //     id: 15,
    //     content: "Luffy_Turnaround.mp4",
    //     contentType: "video",
    //     alt: "Luffy",
    //     category: "art",
    //     skills: ["blender"],
    //     description: "A model of Luffy from One Piece. This was just a fun project to do after learning a lot of useful sculpting techniques over the summer. In the process I learned some really cool ways to create stylized hair as well.",
    // },
    {
        id: 16,
        content: "Train_Turnaround.mp4",
        contentType: "video",
        alt: "Train Model",
        category: "art",
        skills: ["blender"],
        description: "A train model I am working on in Blender to practice Hard Surface modeling. It is still a work in progress. I plan to use it to create a procedural railroad track and have the train follow a drawable track using curves.",
    },
    // {
    //     id: 17,
    //     content: "Pen_Turnaround.mp4",
    //     contentType: "video",
    //     alt: "Pen Shader Turnaround",
    //     category: "art",
    //     skills: ["houdini","substancepainter","maya"],
    //     description: "A pen model and shader made to imitate a real pen I own. The goal was to render the pen onto an image to appear real. Nuke was used a little to blend the lighting and contrast a bit better in the final image.",
    // },
    // {
    //     id: 18,
    //     content: "Kiwi_Turnaround.mp4",
    //     contentType: "video",
    //     alt: "Kiwi Turnaround",
    //     category: "art",
    //     skills: ["houdini", "substancepainter", "maya"],
    //     description: "Kiwi shader. The modeling was done in Maya, the fur and most of the materials/shaders were done in Houdini, and the textures were partially done with Substance Painter.",
    // },
];
module.exports = items;