const languages = [
    {
        id: 0,
        name: "C++",
        logo: "C++.svg",
        experience: "5+ years",
        description: "Used to recreate implementations of data structures and libraries, to learn OpenGL, and for Unreal Engine logic.",
    },
    {
        id: 1,
        name: "Java",
        logo: "java.svg",
        experience: "3+ years",
        description: "Used to create two fully functional Android apps. Used with Maven testing frameworks and JUnit.",
    },
    {
        id: 2,
        name: "Blueprints",
        logo: "unreal.svg",
        experience: "1 year",
        description: "Used for work on Solar Showdown (2023), the video game made by BYU's animation program and for personal projects.",
    },
    {
        id: 3,
        name: "Python",
        logo: "python.svg",
        experience: "2+ years",
        description: "Used for learning AI algorithms, optimization problems, Computer Vision, and Computer graphics.",
    },
    {
        id: 4,
        name: "JavaScript",
        logo: "JavaScript_logo.svg",
        experience: "1 year",
        description: "Used for web development back-end functionality.",
    },
    {
        id: 5,
        name: "HTML",
        logo: "HTML5_logo.svg",
        experience: "1 year",
        description: "Used for web development front-end structure.",
    },
    {
        id: 6,
        name: "CSS",
        logo: "CSS3_logo.svg",
        experience: "1 year",
        description: "Used for web development front-end styling.",
    },
    {
        id: 7,
        name: "Rust",
        logo: "rust_crab.svg",
        experience: "1+ year",
        description: "I built a custom ray-tracer with rust to learn the language. It is becoming one of my favorites. The compiler is awesome and the syntax is easy to read.",
    },
    {
        id: 8,
        name: "C",
        logo: "C_logo.svg",
        experience: "3+ years",
        description: "Used to learn networking, stack overflow problems, and optimizing for compilers.",
    },
    {
        id: 9,
        name: "C#",
        logo: "c-sharp-programming-language-icon.svg",
        experience: "6 months",
        description: "Used for Unity game engine back-end.",
    },
    {
        id: 10,
        name: "SQL/MySQL",
        logo: "mysql.svg",
        experience: "2+ years",
        description: "Used to write to a database for an Android app and learning realtional database models.",
    },
    {
        id: 11,
        name: "Kotlin",
        logo: "Kotlin_Icon.svg",
        experience: "1 month",
        description: "Used to implement a ratings and reviews system for Mutual app which became tonite.",
    },
    {
        id: 12,
        name: "Dart",
        logo: "dart.svg",
        experience: "2 months",
        description: "Used for personal side projects to develop flutter apps.",
    },
];
module.exports = languages;