const languages = [
    {
        id: 0,
        name: "C++",
        logo: "C++_Logo.svg",
        experience: "3+ years",
        description: "Used to recreate implementations of data structures and libraries, to learn OpenGL, and for Unreal Engine logic.",
    },
    {
        id: 1,
        name: "Java",
        logo: "java.svg",
        experience: "3+ years",
        description: "Used to create two fully functional Android apps. Used with Maven testing frameworks and JUnit.",
    },
    {
        id: 2,
        name: "Blueprints",
        logo: "Unreal_Engine_Logo.svg",
        experience: "8 months",
        description: "Used for work on Solar Showdown (2023), the video game made by BYU's animation program and for personal projects.",
    },
    {
        id: 3,
        name: "Python",
        logo: "python.svg",
        experience: "2+ years",
        description: "Used for learning AI algorithms, optimization problems, and Computer graphics.",
    },
    {
        id: 4,
        name: "C",
        logo: "C_logo.svg",
        experience: "3+ years",
        description: "Used to learn networking, stack overflow problems, and optimizing for compilers.",
    },
    {
        id: 5,
        name: "JavaScript",
        logo: "JavaScript_logo.svg",
        experience: "1 year",
        description: "Used for web development back-end functionality.",
    },
    {
        id: 6,
        name: "HTML5",
        logo: "HTML5_logo.svg",
        experience: "1 year",
        description: "Used for web development front-end.",
    },
    {
        id: 7,
        name: "CSS",
        logo: "CSS3_logo.svg",
        experience: "1 year",
        description: "Used for web development front-end.",
    },
    {
        id: 8,
        name: "C#",
        logo: "c-sharp-programming-language-icon.svg",
        experience: "6 months",
        description: "Used to learn Unity game engine back-end as well as a replacement for java.",
    },
    {
        id: 9,
        name: "SQL/MySQL",
        logo: "mysql.svg",
        experience: "2+ years",
        description: "Used to write to a database for an Android app and learning realtional database models.",
    },
    {
        id: 10,
        name: "Kotlin",
        logo: "Kotlin_Icon.svg",
        experience: "1 month",
        description: "Currently being used to implement a ratings and reviews system for Mutual's sister app MutualDates.",
    },
    {
        id: 11,
        name: "Dart",
        logo: "dart.svg",
        experience: "2 months",
        description: "Currently being used for personal side projects to develop flutter apps.",
    },
];
module.exports = languages;