const software = [
    {
        id: 0,
        name: "Blender",
        logo: "blender.svg",
        category: "3D",
        experience: "8+ years",
        description: "Used for Modeling, Rigging, UV Editing, Texturing, Lighting, Rendering, Procedural Geometry, and Sculpting",
    },
    {
        id: 1,
        name: "Unreal Engine",
        logo: "unreal.svg",
        category: "3D",
        experience: "2 years",
        description: "Used for game development projects and for developing Solar Showdown (2023) with BYU's animation department.",
    },
    {
        id: 2,
        name: "Maya",
        logo: "maya.svg",
        category: "3D",
        experience: "3+ years",
        description: "Used for Modeling, Rigging, UV Editing, Lighting, and Rendering",
    },
    
    {
        id: 3,
        name: "Houdini",
        logo: "houdini.svg",
        category: "3D",
        experience: "2 years",
        description: "Used for Procedural Shaders.",
    },
    {
        id: 4,
        name: "Visual Studio Code",
        logo: "vscode.svg",
        category: "cs",
        experience: "4+ years",
        description: "My main IDE/Text Editor for code. I am very experienced with using several different extentions like docker, mongo atlas, and remote ssh.",
    },
    {
        id: 5,
        name: "Visual Studio",
        logo: "vs.svg",
        category: "cs",
        experience: "3+ years",
        description: "Used as my main IDE for daily C++ work",
    },
    {
        id: 6,
        name: "3D Substance Painter",
        logo: "substancepainter.svg",
        category: "3D",
        experience: "1 year",
        description: "Used for texturing and multi-layered shaders.",
    },
    {
        id: 7,
        name: "IntelliJ",
        logo: "intellij.svg",
        category: "cs",
        experience: "2+ years",
        description: "Used as my main IDE for two Android apps.",
    },
    {
        id: 8,
        name: "Android Studio",
        logo: "android.svg",
        category: "cs",
        experience: "2+ years",
        description: "Used as my main IDE for two Android apps alongside Intellij, as well as for working on the MutualDates app.",
    },
    {
        id: 9,
        name: "Amazon Web Services",
        logo: "aws.svg",
        category: "cs",
        experience: "1 year",
        description: "Experience with EC2 web servers, API Gateway, DynamoDB, S3 for large file storage, and Route 53 for managing web domains.",
    },
    {
        id: 10,
        name: "Docker",
        logo: "docker.svg",
        category: "cs",
        experience: "1 year",
        description: "Used for makeing a clean environment for testing with Maven and for learning database management",
    },

];
module.exports = software;