const tools = [
    {
        id: 0,
        name: "Bash",
        logo: "Gnu-bash-logo.svg",
        category: "cs",
        experience: "3+ years",
        description: "Used to naviate linux, write scripts, connect to remote servers, run commandline programs.",
    },
    {
        id: 1,
        name: "Node/NPM",
        logo: "Node.js_logo.svg",
        category: "cs",
        experience: "2+ years",
        description: "Used as a package manager for web development with both Vue and React.",
    },
    {
        id: 2,
        name: "React",
        logo: "logo.svg",
        category: "cs",
        experience: "2 months",
        description: "Used to create this portfolio and the framework we use for CS260, the class that I am a TA for.",
    },
    {
        id: 3,
        name: "Vue",
        logo: "vue_logo.svg",
        category: "cs",
        experience: "3 months",
        description: "Used for web development on the front-end.",
    },
    {
        id: 4,
        name: "MongoDB",
        logo: "mongodb.svg",
        category: "cs",
        experience: "1 year",
        description: "Used as a back-end database for web development.",
    },
    {
        id: 5,
        name: "Caddy",
        logo: "Caddy_logo.svg",
        category: "cs",
        experience: "3 months",
        description: "Used as a web server with automatic HTTPS certification.",
    },
    {
        id: 6,
        name: "Git/Github",
        logo: "github.svg",
        category: "cs",
        experience: "3+ years",
        description: "Used to store projects, keep version history, serve this website through github pages, and collaborate on projects.",
    },
];
module.exports = tools;