const wips = [
    {
        id: 0,
        content: "claw2.jpg",
        contentType: "image",
        alt: "clawcloseup",
        category: "art",
        description: "A simple Blender model of a mailbox made in about 15 minutes",
    },
    {
        id: 1,
        content: "Madeline_Turnaround.mp4",
        contentType: "video",
        alt: "Madeline from Celeste",
        category: "art",
        description: "A sculpt made of the character Madeline from Celeste I made over the summer. Sculpting, Modeling, and Texturing done in Blender",
    },
    {
        id: 2,
        content: "InsectProject.jpg",
        contentType: "image",
        alt: "Insect Project",
        category: "art",
        description: "As a part of CSANM 354, we were given the task of recreating an object in real life to blend into a photograph. The pen in the image is CGI and was modeled and shaded by me. The modeling was done in Blender, the shaders were painted on in Substance Painter, and the image composition was done in Nuke.",
    },
    {
        id: 3,
        content: "SparksSim.mp4",
        contentType: "video",
        alt: "Sparks Simulation",
        category: "art",
        description: "As a part of CSANM 354, we were given the task of recreating an object in real life to blend into a photograph. The pen in the image is CGI and was modeled and shaded by me. The modeling was done in Blender, the shaders were painted on in Substance Painter, and the image composition was done in Nuke.",
    },
    {
        id: 4,
        content: "SmokeSim.mp4",
        contentType: "video",
        alt: "Smoke Simulation",
        category: "art",
        description: "As a part of CSANM 354, we were given the task of recreating an object in real life to blend into a photograph. The pen in the image is CGI and was modeled and shaded by me. The modeling was done in Blender, the shaders were painted on in Substance Painter, and the image composition was done in Nuke.",
    },
    {
        id: 5,
        content: "FlagSim.mp4",
        contentType: "video",
        alt: "Flag Cloth Simulation",
        category: "art",
        description: "As a part of CSANM 354, we were given the task of recreating an object in real life to blend into a photograph. The pen in the image is CGI and was modeled and shaded by me. The modeling was done in Blender, the shaders were painted on in Substance Painter, and the image composition was done in Nuke.",
    },
    {
        id: 6,
        content: "ShatterSim.mp4",
        contentType: "video",
        alt: "Shatter Simulation",
        category: "art",
        description: "As a part of CSANM 354, we were given the task of recreating an object in real life to blend into a photograph. The pen in the image is CGI and was modeled and shaded by me. The modeling was done in Blender, the shaders were painted on in Substance Painter, and the image composition was done in Nuke.",
    },
    {
        id: 7,
        content: "penImage.jpg",
        contentType: "image",
        alt: "Pen Shader",
        category: "art",
        description: "As a part of CSANM 354, we were given the task of recreating an object in real life to blend into a photograph. The pen in the image is CGI and was modeled and shaded by me. The modeling was done in Blender, the shaders were painted on in Substance Painter, and the image composition was done in Nuke.",
    },
    {
        id: 8,
        content: "legoProject.jpg",
        contentType: "image",
        alt: "Lego Smash Bros.",
        category: "art",
        description: "Models I created in CSANM 150 for the Lego Project. All modeling, texture work, lighting, and rendering were done in Maya.",
    },
    {
        id: 9,
        content: "fire_hydrant.png",
        contentType: "image",
        alt: "Fire Hydrant",
        category: "art",
        description: "More modeling practice in Blender",
    },
    {
        id: 10,
        content: "ipod.jpg",
        contentType: "image",
        alt: "iPod",
        category: "art",
        description: "Modeled and textured in Blender based on my own iPod touch.",
    },
    {
        id: 11,
        content: "TrafficLight_Turnaround.mp4",
        contentType: "video",
        alt: "Traffic Light Model",
        category: "art",
        description: "Some basic modeling and shaders made in Blender.",
    },
    {
        id: 12,
        content: "mailbox.png",
        contentType: "image",
        alt: "Mailbox",
        category: "art",
        description: "A simple Blender model of a mailbox made in about 15 minutes",
    },
    {
        id: 13,
        content: "silo6.jpg",
        contentType: "image",
        alt: "silocloseup",
        category: "art",
        description: "A simple Blender model of a mailbox made in about 15 minutes",
    },
];
module.exports = wips;